
/**
 * ProjectManager API for Java
 *
 * (c) ProjectManager.com, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     ProjectManager.com <support@projectmanager.com>
 * @copyright  ProjectManager.com, Inc.
 * @link       https://github.com/projectmgr/projectmanager-sdk-java
 */


package com.projectmanager.models;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * A single planned allocation for a Resource on a Task, on a specific date.
 */
public class ResourceWorkloadAllocationDto
{
    private @NotNull String id;
    private @NotNull String taskId;
    private @NotNull String taskAssignmentId;
    private @NotNull String date;
    private @NotNull Integer minutes;
    private @NotNull Boolean isSystem;
    private @Nullable ResourceWorkloadTaskDetailsDto task;
    private @Nullable ResourceWorkloadTaskAssignmentDto assignment;

    /**
     * Primary constructor
     */
    public ResourceWorkloadAllocationDto() {
    }

    /**
     * The unique identifier of this allocation, which is a combination of the TaskAssignmentId and the Date.
     *
     * @return The field id
     */
    public @NotNull String getId() { return this.id; }
    /**
     * The unique identifier of this allocation, which is a combination of the TaskAssignmentId and the Date.
     *
     * @param value The new value for id
     */
    public void setId(@NotNull String value) { this.id = value; }
    /**
     * The unique identifier of the Task this allocation belongs to.
     *
     * @return The field taskId
     */
    public @NotNull String getTaskId() { return this.taskId; }
    /**
     * The unique identifier of the Task this allocation belongs to.
     *
     * @param value The new value for taskId
     */
    public void setTaskId(@NotNull String value) { this.taskId = value; }
    /**
     * The unique identifier of the TaskAssignment this allocation belongs to.
     *
     * @return The field taskAssignmentId
     */
    public @NotNull String getTaskAssignmentId() { return this.taskAssignmentId; }
    /**
     * The unique identifier of the TaskAssignment this allocation belongs to.
     *
     * @param value The new value for taskAssignmentId
     */
    public void setTaskAssignmentId(@NotNull String value) { this.taskAssignmentId = value; }
    /**
     * The date this allocation applies to.
     *
     * @return The field date
     */
    public @NotNull String getDate() { return this.date; }
    /**
     * The date this allocation applies to.
     *
     * @param value The new value for date
     */
    public void setDate(@NotNull String value) { this.date = value; }
    /**
     * The number of minutes assigned on this date.
     *
     * @return The field minutes
     */
    public @NotNull Integer getMinutes() { return this.minutes; }
    /**
     * The number of minutes assigned on this date.
     *
     * @param value The new value for minutes
     */
    public void setMinutes(@NotNull Integer value) { this.minutes = value; }
    /**
     * True if this allocation was generated by the system rather than manually set.
     *
     * @return The field isSystem
     */
    public @NotNull Boolean getIsSystem() { return this.isSystem; }
    /**
     * True if this allocation was generated by the system rather than manually set.
     *
     * @param value The new value for isSystem
     */
    public void setIsSystem(@NotNull Boolean value) { this.isSystem = value; }
    /**
     * Basic details about the Task. Only populated when the request specifies `include=task`.
     *
     * @return The field task
     */
    public @Nullable ResourceWorkloadTaskDetailsDto getTask() { return this.task; }
    /**
     * Basic details about the Task. Only populated when the request specifies `include=task`.
     *
     * @param value The new value for task
     */
    public void setTask(@Nullable ResourceWorkloadTaskDetailsDto value) { this.task = value; }
    /**
     * Details about the TaskAssignment. Only populated when the request specifies `include=taskAssignment`.
     *
     * @return The field assignment
     */
    public @Nullable ResourceWorkloadTaskAssignmentDto getAssignment() { return this.assignment; }
    /**
     * Details about the TaskAssignment. Only populated when the request specifies `include=taskAssignment`.
     *
     * @param value The new value for assignment
     */
    public void setAssignment(@Nullable ResourceWorkloadTaskAssignmentDto value) { this.assignment = value; }
};
